project:
  type: website

execute: 
  eval: true
  echo: true
  output: true

editor_options: 
  chunk_output_type: inline

website:
  title: "Mathematical Reasoning 2023"
  navbar:
    left: 
      - sidebar:proplog
      - sidebar:fol
      - sidebar:arithmetic
      - sidebar:geom
      - sidebar:reals
      - sidebar:comb
      - sidebar:sets
  sidebar:
    - id: proplog
      title: "Prop. Logic"
      style: "docked"
      background: light
      collapse-level: 3
      contents:
        - prop_log\ancient_greek.qmd
        - prop_log\core_examples.qmd
        - prop_log\abstract_propositions.qmd
        - prop_log\parse_tree.qmd
        - prop_log\eval.qmd
        - prop_log\op_props.qmd
        - prop_log\deduction.qmd
        - prop_log\axiom_systems.qmd
    - id: fol
      title: "FOL"
      style: "docked"
      background: light
      collapse-level: 3
      contents: 
        - fol\pred.qmd
    - id: arithmetic
      title: "Arithmetic"
      style: "docked"
      background: light
      contents: 
        - ari\axioms.qmd
    - id: geom
      title: "Geometry"
    - id: reals
      title: "Reals"
    - id: comb
      title: "Combinatorics"
    - id: sets
      title: "Set Theory"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 3
    code-fold: true

jupyter: python3
monobackgroundcolor: "#f9f9f9"
code-block-border-left: "#31BAE9"
highlight-style: arrow
